### ISSUE TITLE
scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found

### ISSUE THREAD

**Issue by prayagupa** [prayagupd/eccount-rest#1]
```
[INFO] Checking for multiple versions of scala
[WARNING]  Expected all dependencies to require Scala version: 2.11.1
[WARNING]  com.prayagupd.api:rest-api:0.1.0 requires scala version: 2.11.1
[WARNING]  org.scala-lang:scala-compiler:2.11.1 requires scala version: 2.11.1
[WARNING]  org.scala-lang:scala-reflect:2.11.1 requires scala version: 2.11.1
[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.2 requires scala version: 2.11.1
[WARNING]  org.scala-lang.modules:scala-parser-combinators_2.11:1.0.1 requires scala version: 2.11.0
[WARNING] Multiple versions of scala libraries detected!
[INFO] includes = [**/*.java,**/*.scala,]
[INFO] excludes = []
[INFO] /Users/a1353612/buybest/sc212/eccount-rest/src/test/java:-1: info: compiling
[INFO] /Users/a1353612/buybest/sc212/eccount-rest/src/test/scala:-1: info: compiling
[INFO] Compiling 3 source files to /Users/a1353612/buybest/sc212/eccount-rest/target/test-classes at 1510037472462
[ERROR] error: error while loading <root>, Error accessing /Users/a1353612/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/8.5.11/tomcat-embed-core-8.5.11.jar
[ERROR] error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
[INFO] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
[INFO] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[INFO] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
[INFO] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
[INFO] 	at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
[INFO] 	at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
[INFO] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
[INFO] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
[INFO] 	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1376)
[INFO] 	at scala.tools.nsc.Global$Run.<init>(Global.scala:1278)
[INFO] 	at scala.tools.nsc.Driver.doCompile(Driver.scala:33)
[INFO] 	at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
[INFO] 	at scala.tools.nsc.Driver.process(Driver.scala:55)
[INFO] 	at scala.tools.nsc.Driver.main(Driver.scala:68)
[INFO] 	at scala.tools.nsc.Main.main(Main.scala)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at org_scala_tools_maven_executions.MainHelper.runMain(MainHelper.java:161)
[INFO] 	at org_scala_tools_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.494 s
[INFO] Finished at: 2017-11-06T22:51:13-08:00
[INFO] Final Memory: 37M/414M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scala-tools:maven-scala-plugin:2.15.0:testCompile (default) on project rest-api: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1(Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

**Comment by prayagupa** [comment]
Solution
----------

weird but updated scala version, 

```xml
        <dependency>                                                                                   
            <groupId>org.scala-lang</groupId>                                                          
            <artifactId>scala-compiler</artifactId>                                                    
            <version>2.12.4</version>                                                                  
            <scope>compile</scope>                                                                     
        </dependency>                                                                                  
                                                                                                       
        <dependency>                                                                                   
            <groupId>org.scalactic</groupId>                                                           
            <artifactId>scalactic_2.12</artifactId>                                                    
            <version>3.0.0</version>                                                                   
            <scope>test</scope>                                                                        
        </dependency>                                                                                  
                                                                                                       
        <dependency>                                                                                   
            <groupId>org.scalatest</groupId>                                                           
            <artifactId>scalatest_2.12</artifactId>                                                    
            <version>3.0.0</version>                                                                   
            <scope>test</scope>                                                                        
        </dependency>  
```

Then got , 

```
[INFO] Compiling 4 source files to /Users/a1353612/buybest/sc212/eccount-rest/target/classes at 1510037736132
[ERROR] error: scala.reflect.internal.FatalError: Error accessing /Users/a1353612/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/8.5.11/tomcat-embed-core-8.5.11.jar
[INFO] 	at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$list$1(AggregateClassPath.scala:79)
[INFO] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[INFO] 	at scala.collection.Iterator.foreach(Iterator.scala:929)
[INFO] 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
[INFO] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[INFO] 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[INFO] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[INFO] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[INFO] 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[INFO] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[INFO] 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[INFO] 	at scala.tools.nsc.classpath.AggregateClassPath.list(AggregateClassPath.scala:74)
[INFO] 	at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader.doComplete(SymbolLoaders.scala:271)
[INFO] 	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:220)
[INFO] 	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1530)
[INFO] 	at scala.reflect.internal.Mirrors$RootsBase.init(Mirrors.scala:225)
[INFO] 	at scala.tools.nsc.Global.rootMirror$lzycompute(Global.scala:65)
[INFO] 	at scala.tools.nsc.Global.rootMirror(Global.scala:63)
[INFO] 	at scala.tools.nsc.Global.rootMirror(Global.scala:36)
[INFO] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:267)
[INFO] 	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:267)
[INFO] 	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1422)
[INFO] 	at scala.tools.nsc.Global$Run.<init>(Global.scala:1164)
[INFO] 	at scala.tools.nsc.Driver.doCompile(Driver.scala:34)
[INFO] 	at scala.tools.nsc.MainClass.doCompile(Main.scala:24)
[INFO] 	at scala.tools.nsc.Driver.process(Driver.scala:55)
[INFO] 	at scala.tools.nsc.Driver.main(Driver.scala:68)
[INFO] 	at scala.tools.nsc.Main.main(Main.scala)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at org_scala_tools_maven_executions.MainHelper.runMain(MainHelper.java:161)
[INFO] 	at org_scala_tools_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[ERROR] Caused by: java.io.IOException: Error accessing /Users/a1353612/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/8.5.11/tomcat-embed-core-8.5.11.jar
[INFO] 	at scala.reflect.io.FileZipArchive.scala$reflect$io$FileZipArchive$$openZipFile(ZipArchive.scala:128)
[INFO] 	at scala.reflect.io.FileZipArchive.x$2$lzycompute(ZipArchive.scala:164)
[INFO] 	at scala.reflect.io.FileZipArchive.x$2(ZipArchive.scala:161)
[INFO] 	at scala.reflect.io.FileZipArchive.allDirs$lzycompute(ZipArchive.scala:161)
[INFO] 	at scala.reflect.io.FileZipArchive.allDirs(ZipArchive.scala:161)
[INFO] 	at scala.tools.nsc.classpath.ZipArchiveFileLookup.findDirEntry(ZipArchiveFileLookup.scala:71)
[INFO] 	at scala.tools.nsc.classpath.ZipArchiveFileLookup.list(ZipArchiveFileLookup.scala:52)
[INFO] 	at scala.tools.nsc.classpath.ZipArchiveFileLookup.list$(ZipArchiveFileLookup.scala:51)
[INFO] 	at scala.tools.nsc.classpath.ZipAndJarClassPathFactory$ZipArchiveClassPath.list(ZipAndJarFileLookupFactory.scala:42)
[INFO] 	at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$list$1(AggregateClassPath.scala:76)
[INFO] 	... 33 more
[INFO] Caused by: java.util.zip.ZipException: zip file is empty
[INFO] 	at java.util.zip.ZipFile.open(Native Method)
[INFO] 	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
[INFO] 	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
[INFO] 	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
[INFO] 	at scala.reflect.io.FileZipArchive.scala$reflect$io$FileZipArchive$$openZipFile(ZipArchive.scala:126)
```


Deleting `rm -rf /Users/a1353612/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/8.5.11/` works fine.
